env_name: 'stick-pull-v3-goal-observable'
env_type: 'metaworld'
act_type: 'Tanh'
n_steps: 1e6
g: 0.99
lm: 0.95
u_epi_ups: 0
bs: 2048
n_itrs: 10
n_slices: 16
lr: 0.0003
h_dim: [256, 256, 256]
u_adv_scl: 1
clip_eps: 0.2
ob_norm: 0
rew_norm: 0
dir: 'data/metaworld/stick-pull/'
to_log: []
label: 'PPO stick-pull'
